[package]
name = "power_opts"
version = "0.1.0"
edition = "2021"

[dependencies]
log = {workspace = true}
colog = {workspace = true}
serde = {workspace = true}
serde_yaml = {workspace = true}
clap = {workspace = true}
rustix = {workspace = true}
init_system = {workspace = true}